
all:
	cd I && make && cd ../II && make && cd ../III && make && cd ../IV && make && cd ../V && make && cd ../VI && make

clean:
	cd I && make clean && cd ../II && make clean && cd ../III && make clean && cd ../IV && make clean && cd ../V && make clean && cd ../VI && make clean
